server:
    port: 8085

spring:
    profiles:
        include:
            - dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ms_multiplication?useSSL=false
        username: root
        password: root
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

# expose all the Actuator endpoints
management:
    endpoints:
        web:
            exposure:
                include: "*"
